CREATE DATABASE credit_risk_db;
USE credit_risk_db;

-- Internal Bank Table
CREATE TABLE internal_bank (
    PROSPECTID INT PRIMARY KEY,
    Total_TL INT,
    Tot_Closed_TL INT,
    Tot_Active_TL INT,
    Total_TL_opened_L6M INT,
    Tot_TL_closed_L6M INT,
    pct_tl_open_L6M FLOAT,
    pct_tl_closed_L6M FLOAT,
    pct_active_tl FLOAT,
    pct_closed_tl FLOAT,
    Total_TL_opened_L12M INT,
    Tot_TL_closed_L12M INT,
    pct_tl_open_L12M FLOAT,
    pct_tl_closed_L12M FLOAT,
    Tot_Missed_Pmnt INT,
    Auto_TL INT,
    CC_TL INT,
    Consumer_TL INT,
    Gold_TL INT,
    Home_TL INT,
    PL_TL INT,
    Secured_TL INT,
    Unsecured_TL INT,
    Other_TL INT,
    Age_Oldest_TL INT,
    Age_Newest_TL INT
);

-- External CIBIL Table
CREATE TABLE external_cibil (
    PROSPECTID INT PRIMARY KEY,
    time_since_recent_payment FLOAT,
    time_since_first_deliquency FLOAT,
    time_since_recent_deliquency FLOAT,
    num_times_delinquent INT,
    max_delinquency_level FLOAT,
    max_recent_level_of_deliq FLOAT,
    num_deliq_6mts INT,
    num_deliq_12mts INT,
    num_deliq_6_12mts INT,
    max_deliq_6mts FLOAT,
    max_deliq_12mts FLOAT,
    num_times_30p_dpd INT,
    num_times_60p_dpd INT,
    num_std INT,
    num_std_6mts INT,
    num_std_12mts INT,
    num_sub INT,
    num_sub_6mts INT,
    num_sub_12mts INT,
    num_dbt INT,
    num_dbt_6mts INT,
    num_dbt_12mts INT,
    num_lss INT,
    num_lss_6mts INT,
    num_lss_12mts INT,
    recent_level_of_deliq FLOAT,
    tot_enq FLOAT,
    CC_enq FLOAT,
    CC_enq_L6m FLOAT,
    CC_enq_L12m FLOAT,
    PL_enq FLOAT,
    PL_enq_L6m FLOAT,
    PL_enq_L12m FLOAT,
    time_since_recent_enq FLOAT,
    enq_L12m FLOAT,
    enq_L6m FLOAT,
    enq_L3m FLOAT,
    MARITALSTATUS VARCHAR(20),
    EDUCATION VARCHAR(30),
    AGE INT,
    GENDER VARCHAR(5),
    NETMONTHLYINCOME FLOAT,
    Time_With_Curr_Empr FLOAT,
    pct_of_active_TLs_ever FLOAT,
    pct_opened_TLs_L6m_of_L12m FLOAT,
    pct_currentBal_all_TL FLOAT,
    CC_utilization FLOAT,
    CC_Flag INT,
    PL_utilization FLOAT,
    PL_Flag INT,
    pct_PL_enq_L6m_of_L12m FLOAT,
    pct_CC_enq_L6m_of_L12m FLOAT,
    pct_PL_enq_L6m_of_ever FLOAT,
    pct_CC_enq_L6m_of_ever FLOAT,
    max_unsec_exposure_inPct FLOAT,
    HL_Flag INT,
    GL_Flag INT,
    last_prod_enq2 VARCHAR(30),
    first_prod_enq2 VARCHAR(30),
    Credit_Score INT,
    Approved_Flag VARCHAR(5)
);